export default data=[
    {
        id:0,
        question: "Argentina",
        correctOptionId:3,
        options:[
            {
                optionId:0,
                imgUrl:require("../assets/images/aww.png")
            },
            {
                optionId:1,
                imgUrl:require("../assets/images/greece.png")
            },
            {
                optionId:2,
                imgUrl:require("../assets/images/bww.png")
            },
            {
                optionId:3,
                imgUrl:require("../assets/images/ar.png")
            }
        ]
    },
    {
        id:1,
        question: "USA",
        correctOptionId:2,
        options:[
            {
                optionId:0,
                imgUrl:require("../assets/images/lr.png")
            },
            {
                optionId:1,
                imgUrl:require("../assets/images/my.png")
            },
            {
                optionId:2,
                imgUrl:require("../assets/images/us.png")
            },
            {
                optionId:3,
                imgUrl:require("../assets/images/xk.png")
            }
        ]
    }
]